### ISSUE TITLE
Other connected repos

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/evolution#1]
Some files moved from **maptools**: https://github.com/rsbivand/sp/tree/retiring and rgdal/rgeos/maptools removed from DESCRIPTION: currently broken, work-in-progress.

https://github.com/rsbivand/sf_asdar2ed ASDAR code to run without proxy but with sp retired branch, using **sf** instead of rgdal/rgeos/maptools, work-in-progress and needs `sp::spTransform()` to be rewritten to use `sf::st_transform()`, `sp::CRS()` to use `sf::st_crs()`. Much use of `sf::st_as_sf()` and coercion from `"sf"` to `"Spatial"`. With comments suggests how **sp** workflows might continue without immediate full **sf** conversion.

One note for stars: coercion from multiband `"stars"` to "Spatial"` seems to need to `cbind()` each coerced array slice band separately.

Loose question - what about **spacetime**?

**Comment by edzer** [comment]
> Loose question - what about spacetime?

in short: `stars` replaces the `STFDF`, [`sftime`](https://github.com/r-spatial/sftime) is meant to replace `STIDF`, and `STSDF` was a special case of `STFDF` anyway (and hence isn't continued).

**Comment by rsbivand** [comment]
if/when **sftime** gets to CRAN, should it be folded into comments in the ASDAR code? I anticipate the current sp-style ASDAR code to continue running more or less as before, but  a second set of chapter files could show how to use currently preferred packages rather than **sp**. The first cut is to guide minimal adaptation to rgdal/rgeos/maptools retiring, the raise-your-game cut is to step away from **sp**.
