### ISSUE TITLE
`sp::is.projected()` dependence on sf

### ISSUE THREAD

**Issue by bastistician** [r-spatial/evolution#10]
With the current implementation of [evolution status 2 in `sp:::is.projectedCRS()`](https://github.com/edzer/sp/blob/aa25d97ed470a4769f3df09b8c573730bc81b104/R/projected.R#L117-L119), **sp** is barely useable without **sf**:

```R
options(sp_evolution_status = 2)
library("sp")
data(wrld_simpl, package = "maptools")
summary(wrld_simpl)
## Error in is.projected(p4str) : sf required for evolution_status==2L
plot(wrld_simpl)
## Error in is.projected(p4str) : sf required for evolution_status==2L
```

It essentially only works for Spatial objects with unknown projection `CRS(NA_character_)` (https://github.com/edzer/sp/issues/125).

Previously, `rgdal::OSRIsProjected()` was used, but with simple fallbacks for when **rgdal** was not available (e.g., grepping for "longlat" in projargs or "^GEO" in wkt2). Will these fallbacks be resurrected for when **sf** is not available? Or will **sp** import **sf**?

**Comment by edzer** [comment]
Not import as in `Imports:`, but it will need it for anything that has to do with CRS objects now handled by `rgdal`.

**Comment by bastistician** [comment]
So this means the fallbacks will be enabled like for **rgdal**? If not, I think (but @rsbivand will know better) that many of **sp**'s revdeps would have to import or suggest+conditionalize **sf** themselves in the future -- given that such central methods like `plot()` and `summary()` would not work without it.

**Comment by rsbivand** [comment]
Yes, roughly by June 2023. Warning them to upgrade is our next task after the currently ongoing campaign to de-couple packages using raster, which now uses terra not rgdal/rgeos, to drop them as Suggests:. More details in https://r-spatial.org/r/2022/12/14/evolution2.html.

**Comment by bastistician** [comment]
Good to know. Thanks for giving the maintainers so much lead time!

**Comment by bastistician** [comment]
> many of **sp**'s revdeps would have to import or suggest+conditionalize **sf** themselves in the future -- given that such central methods like `plot()` and `summary()` would not work without it.

FWIW, I have just checked 322 of 597 direct **sp** revdeps from CRAN and BioC (as at 6 June 11:00 CEST) under **sp** 1.6-1 patched with `assign("evolution_status", 2L, envir=.spOptions)` and `_R_CHECK_SUGGESTS_ONLY_=true`. This found problems with
```
Check                             ERROR
  examples                           19
  re-building of vignette outputs     6
  tests                               3
```
in the following 20 packages: SeerMapper, SeerMapper2010East, SeerMapper2010Regs, SeerMapper2010West, SeerMapperEast, SeerMapperRegs, SeerMapperWest, SiMRiv, aqp, hhh4contacts, loa, maptools, marmap, overlap, phyloregion, rgeos, rworldmap, soilassessment, spatsoc, trip.
All errors were `Error in is.projected(p4str) : sf required for evolution_status==2L`, mostly from trying to `plot()` or `spplot()`. Hope this helps! (It did for me as I wasn't aware that my own hhh4contacts would be affected.)

**Comment by rsbivand** [comment]
Thanks, I'll tally these against my own. `sp200` branch from my `sp` getting ready to release, so very relevant.

**Comment by rsbivand** [comment]
I'm looking at a fix in my fork https://github.com/rsbivand/sp/tree/sp200, commit https://github.com/rsbivand/sp/commit/c12346435d7bfe660f9fd726c8a555eeaf4dd928. It seems to work for `aqp`, I'll try others tomorrow, and check that there are no `stop`s when `sf` is absent.

**Comment by rsbivand** [comment]
Apart from `trip` (tests not expecting warnings), https://github.com/edzer/sp/pull/135/commits/0ec24a333ca4b2c26673300089be6155d849700e and https://github.com/edzer/sp/pull/135/commits/5ec376f1e67bd1f6d9125848fc3da6fd8f237d67 address the issue for the remaining packages.

Output from three settings:

With `sf` on the library path:
```
$ R_LIBS=/home/rsb/lib/r_libs:/home/rsb/lib/r_libs_sf R
...
> library(sp)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
> (crs <- CRS("+proj=longlat +ellps=WGS84"))
Coordinate Reference System:
Deprecated Proj.4 representation: +proj=longlat +ellps=WGS84 +no_defs 
WKT2 2019 representation:
GEOGCRS["unknown",
    DATUM["Unknown based on WGS 84 ellipsoid",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1],
            ID["EPSG",7030]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]] 
> is.projected(crs)
[1] FALSE
```
without `sf` on the library path:
```
$ R_LIBS=/home/rsb/lib/r_libs R
...
> library(sp)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
> (crs <- CRS("+proj=longlat +ellps=WGS84"))
Coordinate Reference System:
Deprecated Proj.4 representation: +proj=longlat +ellps=WGS84 
Warning message:
In CRS("+proj=longlat +ellps=WGS84") : sf required for evolution_status==2L
> is.projected(crs)
[1] FALSE
Warning message:
In is.projected(crs) : Package sf not available
```
without `sf` on the library path and using an environment variable to mute noise:
```
_SP_STARTUP_MESSAGE_="none" R_LIBS=/home/rsb/lib/r_libs R
...
> library(sp)
> (crs <- CRS("+proj=longlat +ellps=WGS84"))
Coordinate Reference System:
Deprecated Proj.4 representation: +proj=longlat +ellps=WGS84 
> is.projected(crs)
[1] FALSE
```

**Comment by bastistician** [comment]
I can confirm that <https://github.com/edzer/sp/pull/135/commits/0ec24a333ca4b2c26673300089be6155d849700e> fixes all "noSuggests" problems that I had reported above: I re-checked the same set of packages using your sp200 branch and found no changes to worse except for the known trip issue.
