### ISSUE TITLE
request to include mssql driver in sf/terra 

### ISSUE THREAD

**Issue by cmundy** [r-spatial/evolution#11]
Hi,

For many years I have taken advantage of the sp/rgdal/rgeos suite of packages for my spatial needs. I have been watching the progression of sf/terra and updating all my scripts as can. The one hiccup I have encountered so far is that the drive for mssql is not included in sf a this point (mssqlSpatial is still supported by gdal/ogr).

Is it possible to flag the inclusion of the ogr drive for mssql spatial please?

Thanks Craig

ps and many thanks for the r-spatial packages over the past 15 years!

**Comment by rsbivand** [comment]
The driver list depends only on the GDAL build. Please show the session.info() of the platform where it is present and where you now think it is absent. I guess there may be a difference between R 4.1 and R 4.2 on Windows, or between x86_64 and aarch on macOS, but you do not state your platforms.

**Comment by cmundy** [comment]
My apologies Roger,

> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8
[3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C
[5] LC_TIME=English_Australia.utf8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2


> library(sf)
Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE
> library(terra)
terra 1.7.3

Session info below. Yes I do think it’s a platform issue.

At the following link the  MSSQLSpatial driver appears in the list.

Complete list of drivers from my machine using st_drivers(what = "vector")

name
AVCBin
AVCE00
AmigoCloud
BAG
CAD
CSV
CSW
Carto
DGN
DXF
EDIGEO
EEDA
ESRI Shapefile
ESRIC
ESRIJSON
Elasticsearch
FlatGeobuf
GML
GPKG
GPSBabel
GPX
GeoJSON
GeoJSONSeq
GeoRSS
Geoconcept
HTTP
Idrisi
JML
JP2OpenJPEG
KML
LVBAG
MBTiles
MVT
MapInfo File
MapML
Memory
MySQL
NGW
OAPIF
ODS
OGCAPI
OGR_GMT
OGR_PDS
OGR_SDTS
OGR_VRT
OSM
OpenFileGDB
PDF
PDS4
PGDUMP
PLSCENES
S57
SQLite
SVG
SXF
Selafin
TIGER
TopoJSON
UK .NTF
VDV
VFK
VICAR
WAsP
WFS
XLS
XLSX
netCDF

**Comment by cmundy** [comment]
Apologies,

End of a long day.

Mssqlspatial appears in this list
https://r-spatial.github.io/sf/reference/st_drivers.html

**Comment by edzer** [comment]
See also https://github.com/r-spatial/sf/issues/2088

**Comment by rsbivand** [comment]
`"MSSQLSpatial"` driver is in Rtools43, so is in packages built for forthcoming R 4.3 on Windows.

**Comment by cmundy** [comment]
Thanks all for your help – much appreciated.

And thanks again for all your work in R-spatial.

Craig
