### ISSUE TITLE
Can we download the package to the local and install it??

### ISSUE THREAD

**Issue by lyfranki** [r-spatial/evolution#13]
Hello,

Is it still possible to download and install the 'rgdal' package from a local source ('C:/Users/User/Downloads/rgdal_1.6.7.zip') using the command "install.packages('C:/Users/User/Downloads/abc_2.1.zip', repos=NULL, type='source')" even though the package has been retired?

**Comment by edzer** [comment]
Yes you can; in the future with newer R version you may get a warning (first) and later (after a major release) you may get an error when trying to do so.

**Comment by lyfranki** [comment]
Thank you for the clarification @edzer ! So, is it correct to assume that as long as we continue using an older R version like R 3.6, we will be able to install the 'rgdal' package from a local source and run the corresponding code without encountering any issues?

**Comment by rsbivand** [comment]
@lyfranki  "without encountering any issues" is a big ask, and will depend on the states of external libraries like GDAL, GEOS and PROJ. I certainly would not advocate any such policy. Much better to keep current (R 3.6 was released in 2019, last patch release in 2020). If on Windows or macOS, so much has changed that the maintainers can give no assurance at all; all encountered issues would be up to you to address locally.
