### ISSUE TITLE
raster library

### ISSUE THREAD

**Issue by chipsin87** [r-spatial/evolution#14]
I have a lot of scripts that are dependent on the `raster` package (to my knowledge I am not using `rgdal`, `rgeos` or `maptools`). I have seen from the website below that the `raster` package is obsolete and to use `terra` instead. 

https://rspatial.org/raster/

Based on talks I have seen from Rodger Bivand earlier this I have started to only use `terra` for new workflows, except where I have to convert a terra::rast to a raster::raster for things like using `mapview` or use a raster::brick object in mapview.

https://www.youtube.com/watch?v=TlpjIqTPMCA

Do I need to update my old workflows which use raster::raster and raster::brick objects? I am sure this question has been covered (so apologies in advance) but couldn't find anything definitive (and want to make sure my workflows won't fail later this year).

**Comment by tim-salabim** [comment]
Hi @chipsin87 the current development version of mapview on github should handle `terra::rast` objects. What is the equivalent of a `raster::brick` in terra, does anyone know?

**Comment by Nowosad** [comment]
@tim-salabim also `terra::rast()` (In short, the main object class in terra is `SpatRaster`, which replaces RasterLayer, RasterStack, and RasterBrick from raster)

**Comment by tim-salabim** [comment]
Thanks @Nowosad, we should be fine then as the method for `SpatRaster` converts to `stars` internally. Details may need to be worked out, but in principle, things should work.

**Comment by Nowosad** [comment]
Yep

**Comment by rsbivand** [comment]
@tim-salabim is that to `stars` or the proxy variant to be able to rescale on-the-fly?

**Comment by chipsin87** [comment]
Thanks @tim-salabim  for getting back to me so fast. For all new development I will be using 'terra::rast' objects and 'terra' functions. For prioritising work in the coming months though, I'm curious to know if my old code base (which is quite large) will still run using my 'raster::raster' and 'raster::brick' objects and the latest 'raster' functions?

**Comment by tim-salabim** [comment]
@chipsin87 it should, methods for `raster` are still available in mapview.

**Comment by chipsin87** [comment]
@rsbivand, for all my other workflows that use `raster::raster` and `raster::brick` objects with `raster` functions, it will business as usual post October this year? (i.e. no need to update existing code that only uses `raster` objects with `raster` functions?). I am trying to prioritise work for the coming months

**Comment by rsbivand** [comment]
Yes, `raster` has used `terra` in place of retiring packages for almost a year now, so no difficulties should occur.

**Comment by tim-salabim** [comment]
@rsbivand I think it is to stars directly. But I may rethink that anyway over the coming weeks. Leaflet supports terra now so we could write native terra methods. I'll have to investigate the best path forward.
