### ISSUE TITLE
question on miscellaneous functions from rgeos (gArea, gIntersects)  how to access or alternate?

### ISSUE THREAD

**Issue by arcolombo** [r-spatial/evolution#25]
Hi thank you for the great work on these packages and the retirement of rgeos.

my question is that i'm reading code that uses gArea function and gIntersects from rgeos, but am not sure where the replacement is or how to approach that, 

thank you again,
AC

**Comment by Nowosad** [comment]
@arcolombo -- the most straightforward approach is to use the sf package instead of sp/rgdal/rgeos. See a comparison table at https://github.com/r-spatial/sf/wiki/Migrating#relevant-commands-exported-by-rgeos

**Comment by arcolombo** [comment]
thank you please close
