### ISSUE TITLE
Thread on finding functions used by revdep packages

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/evolution#3]
https://stat.ethz.ch/pipermail/r-package-devel/2019q1/003590.html

using **pkgapi**.

**Comment by rsbivand** [comment]
and script used:
[rev-dep.txt](https://github.com/r-spatial/evolution/files/7970218/rev-dep.txt)

**Comment by rsbivand** [comment]
For **maptools** gives:

[res5.pdf](https://github.com/r-spatial/evolution/files/7971114/res5.pdf)

**Comment by rsbivand** [comment]
Yesterday's output for **maptools**, **rgdal** and **rgeos**:
[map_package_220413.zip](https://github.com/r-spatial/evolution/files/8488570/map_package_220413.zip)

(four RDS files by package and an ODS spreadsheet). The absence of `rgdal::spTransform()` in the rgdal suggested that S4 methods are not being detected by `pkgapi::map_packages()`. However, `maptools::elide()` is detected, so the problem here is that `sp::spTransform()` is seen rather than `rgdal::spTransform()`, so the fourth tab in the spreadsheet and RDS file are `sp::` links detected in `"most"` **rgdal** packages; there are 56 packages using `spTransform()` in code.

NOTE: this analysis only considers code; vignettes, examples and demos are omitted.

**Comment by rsbivand** [comment]
Running **pkgapi** 2022-07-13 for CRAN packages, the output is:
[pkgapi_no_sp_220713.csv](https://github.com/r-spatial/evolution/files/9112210/pkgapi_no_sp_220713.csv)
[pkgapi_no_sp_by_pkg_220713.csv](https://github.com/r-spatial/evolution/files/9112212/pkgapi_no_sp_by_pkg_220713.csv)
The first spreadsheet is by retiring package then retiring package function (maptools 40, rgdal 49, rgeos 52) listing the packages using the functions in code, the second spreadsheet is by using package, listing which retiring package functions are used in code (228 packages). This does not pick up functions used in examples, tests, demos or vignettes. File name `no_sp` only indicates that **sp** was not included in these runs.

**Comment by edzer** [comment]
Great! A quarto doc processing these two files is found in [report.qmd](https://github.com/r-spatial/evolution/blob/main/report.qmd), a rendered output [here](https://r-spatial.github.io/evolution/report.html).

**Comment by rsbivand** [comment]
**raster** 3.5-29 on CRAN with among others:
![Screenshot from 2022-08-17 10-09-36](https://user-images.githubusercontent.com/10198404/185068785-daaad761-e7a2-4f34-877b-21f135853a66.png)

**Comment by rsbivand** [comment]
[all_merge_220827.csv](https://github.com/r-spatial/evolution/files/9438561/all_merge_220827.csv)

has revdeps without retiring packages installed and **sp** evoltion status 2 for `packages = c("sp", "maptools", "rgdal", "rgeos", "raster"), which = "most"` with development versions of **raster**, **terra** (and **Matrix** - FRK and IDE fell foul of Matrix >= 1.4-2 changes). 

```
> table(all_merge$errs, addNA(all_merge$type))
       
        no_pkg req_by_req_pkg required <NA>
  FALSE      5              0        0  499
  TRUE      44             19      292   21
```
Of 880 packages, 404 do not fail, but 5 have a "there is no package called" because of missing suggests conditioning somewhere. The remainder split between those depending on or importing retiring packages themselves (required, 292 packages), those depending on or importing packages which themselves depend on or import retiring packages (req_by_req_pkg, 19 packages, showing up as an installation failure), and "there is no package called" errors, often from unconditional use of suggested retiring packages without conditioning on their availability (no_pkg, 44 packages). 

I have not merged these results with the pkgapi results.

**Comment by Nowosad** [comment]
@rsbivand just to let you know -- {rgdal}-less version of {raster} is on CRAN -- https://cran.r-project.org/package=raster.
