### ISSUE TITLE
Policy update?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/evolution#4]
In https://github.com/r-spatial/mapview/issues/418#issuecomment-1100818133, I suggest that: 

> It is likely that retirement will mean archiving the three packages at the latest ultimo 2023. Creating masking sequel packages creates more maintenance, so unless **sp** methods are involved, especially `sp::spTransform()`, the best solution is hard retirement. We'll know more by August this year.

Is this reasonable @edzer @rhijmans ?

I'd like to ask whether the next **sp** release should be from my `evolution` branch (by PR to the  main repo)? 

I'd also like to add deprecation to everything exported by **maptools**, **rgeos** and **rgdal**. However, the `base::.Deprecated()` function is not a good fit, so might it make sense to add a customised function to **sp** since **maptools**, **rgeos** and **rgdal** all depend on **sp**? The **base** function moves all the help pages to for example `rgdal-deprecated`, which seems too invasive at this stage. A deprecation note is more in-your-face than the package startup messages, but isn't yet a full warning triggering CRAN problems when warnings are converted to  errors.

The results in #3 don't cover examples, vignettes, tests or demos, so adding output might add the required noise.

I'm also considering a blog based on the adaptations in the https://github.com/rsbivand/sf_asdar2ed repo; would this make sense?

**Comment by rhijmans** [comment]
I understand that it may not be a good strategy to create masking packages. It should be possible to move on. For `raster`  I should be able to replace rgeos/rgdal with terra methods. It is just a bit of work, so thanks for the heads-up.
