### ISSUE TITLE
rgeos retirement

### ISSUE THREAD

**Issue by mehrnoushmalek** [r-spatial/evolution#5]
Hello,

First of all thanks a lot for creating and maintaining this package all these years.
I'd appreciate it if you can guide me about alternative options for my case described below:
I'm using **sp** package to define polygons, which are the boundaries around the cluster of points in 2D, and then `gIntersects, gDifference,gBuffer, gUnion` from **rgeos** mainly to do polygon manipulation (i.e., union, subtraction and intersection of two polygon), extracting the coordinates of the polygon from these functions, and then using point.in.polygon from **sp** to get indices of point inside the polygon.

I have part of my code  here as well.

 
   ```
  #filter1 and filter 2 are matrices of 2D coordinates
     poly1 <- sp::SpatialPolygons(list(sp::Polygons(list(Polygon(filter1)), ID=c("c"))))  
     poly2 <- sp::SpatialPolygons(list(sp::Polygons(list(Polygon(filter2)), ID=c("c"))))
     if(rgeos::gIntersects( poly1, poly2)){
       temp <-tryCatch(rgeos::gDifference(poly1,poly2), error=function(ex) return(1))
       if (mode(temp)=="numeric")
       {
         temp <- rgeos::gDifference(poly1,rgeos::gBuffer(poly2))
       }
       
       filter<-temp@polygons[[1]]@Polygons[[1]]@coords
    }

```
Since I'm working with biological data, reproducibility is really important, and I'd like to avoid any discrepancy while moving from **rgeos/sp** to another package, so any help would be very much appreciated

**Comment by rsbivand** [comment]
See https://github.com/r-spatial/evolution/issues/3; will try to run analyses today. Note that **rgeos** never provided reproducibility across versions of GEOS, and the GEOS topology engine has been upgraded several times, most recently for OverlayNG in November 2020 (https://libgeos.org/). 

My suspicion is that the choice of **rgeos** might have been provoked by the unfree license of **gpclib**; another choice now is **polyclip**, which does not assume that the data are in spatial classes; it is used by **spatspat** family packages among others. We could work up a migration plan from **rgeos** to **polyclip** for non-spatial uses. One problem is whether polygons include holes or not.

Once the analyses are complete (I'm upgrading to 4.2 and Bioc 3.15 first), we'll see which Bioc packages use **rgeos**, **rgdal** or **maptools** in code.

**Comment by rsbivand** [comment]
Analysis for **rgeos**: only **flowDensity** of all Bioc packages uses **rgeos**: `"rgeos::gIntersects" "rgeos::gDifference" "rgeos::gBuffer"`. No Bioc packages are `"most"` reverse dependent on **rgdal**, only "GEOexplorer" is `"most"` reverse dependent on **maptools**: `"maptools::pointLabel"`. As far as **flowDensity** is concerned, please attempt replacement with **polyclip** and report back.

**Comment by mehrnoushmalek** [comment]
Thanks @rsbivand. To answer your question, polygons in my case don't have holes, but there will be cases that one polygon might be inside the other one while sharing an edge or vertices.
Regarding reproducibility, I didn't mean rgeos is not reproducible, I'd like to use a replacement that won't alter the result much. 
Thanks for the **polyclip**. I will check it and see how it goes, I just need to see how easy it is to use both **sp** and **polyclip** together.

**Comment by rsbivand** [comment]
Briefly, I don't think that **sp** is needed, just objects as specified in **polyclip**.
